server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location = /kargoknot {
        return 301 /kargoknot/;
    }

    location /kargoknot/ {
        try_files $uri $uri/ /index.html;
    }

    location /kargoknot/api/ {
        proxy_pass http://kargoknot-api:8080/api/;
    }
}